* box-course


** Installation
Use pip to install box_course



*** TODO Dependencies
pdftk
PyPDF2
# pdfminer  # not actually using this
requests

*** TODO Register for your box-app
get your client id and secret

*** TODO Setup your webserver, and put the cgi-script there.

** Configuration and course setup


** Course management

You keep a collection of assignments in the /problems folder. You refer to assignments by a "label". When an assignment is created, a folder is created in /assessments/course-andrewid/course-andrewid-label. When you "assign" the problem, students are set to "editors" of their folders. When you "collect" the assignment, they are set to "viewers".

This won't work for exams/quizzes. If the students are viewers of their folder, they can see everything in it I think.


box-course create hello-world.py --message "due on ..."
   this will create /assessments/course-andrewid/course-andrewid-hello-world and copy /problems/hello-world.py into it

box-course create regress-2 --message "due on ..."
   this will create /assessments/course-andrewid/course-andrewid-regress-2 and copy the contents of /problems/regress-2 into it

If there is an actual file called the label, that will be assigned to the students. If a directory exists by that label, then the contents of that directory will be assigned. 

box-course create assessment-label --message "due on ..."
box-course assign assessment-label 
box-course collect assessment-label

box-course timed assessment-label --time N


box-course update-grade-report andrewid

box-course email args --message "to people in args"
* TODO json data
store all the data in JSON instead of shelve

* TODO How to include external students?
one problem is I want to use the course roster, which contains andrewids. I need to include other email addresses too. I could add these to the roster, but they wold be deleted with updates. 

I think I need an extra roster file, with the same format, but with email addresses.


The file needs this format for consistency
year, email, lastname, firstname

F13, johnrkitchin@gmail.com, Kitchin, John
* TODO box-cli
I really want a command line ability to add, remove and edit collaborations, tasks, etc...

box-cli collab --add --remove --edit
box-cli task --add --remove --edit  
